### ISSUE TITLE
App crashes upon clicking the favorite icon

### ISSUE THREAD

**Issue by Ericgacoki** [JoelKanyi/Muviz#20]
```diff
- Bug report 🐛
```
![app crash](https://user-images.githubusercontent.com/54077752/159111126-561410d1-c2b5-4681-bdff-1292f6e72502.png)

`desc:`

The movie details are loaded and displayed quite well. However, when you try to add the movie to your favorites, the app crashes.
Still on that, there's no live update on the icon. Users  would expect to see a different color immediately after clicking the icon - not after refreshing the screen!

`possible fix:`
-  Use Livedata or Flows in conjunction with Coroutines to capture and update the icon state at real time!

**Comment by JoelKanyi** [comment]
Thank you, let me work on this issue

**Comment by JoelKanyi** [comment]
Fixed
