### ISSUE TITLE
BottomNav hides the bottom part of the Top rated movies list

### ISSUE THREAD

**Issue by Ericgacoki** [JoelKanyi/Muviz#22]
![bottom nav](https://user-images.githubusercontent.com/54077752/159111841-ae174f2c-b058-4ae6-b6c8-f43d0743077a.png)

This is the maximum you can scroll to. It would be better to display the whole item and leave a space between the list and the bottom nav!

`possible fix:`
- Play around with the offsets of the parent container upon reaching the last item in the nested scroll or
- Add an empty composable, preferably a Spacer as the last item in the LazyColumn 😂 (i'd go with this one)

**Comment by JoelKanyi** [comment]
Fixed
