### ISSUE TITLE
Vertically scrollable component was measured with an infinity maximum height constraints

### ISSUE THREAD

**Issue by tenSunFree** [JoelKanyi/Muviz#29]
Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()).
<img width="889" alt="0001" src="https://user-images.githubusercontent.com/23090085/159759613-53330125-283c-4d79-b8bd-b36d1876978d.png">

You can try removing verticalScroll(), because LazyColumn already provides scrolling.
<img width="484" alt="0002" src="https://user-images.githubusercontent.com/23090085/159759887-d4a99331-77a3-47dd-86c6-a0c79c3685a7.png">

**Comment by JoelKanyi** [comment]
Thank you @tenSunFree, which screen is this

**Comment by JoelKanyi** [comment]
Hello @tenSunFree, I removed this feature for now, that version of code that you have is not the current one. Please update

**Comment by tenSunFree** [comment]
I understand, but I think the previous "See more" feature is pretty good, thank you.

**Comment by JoelKanyi** [comment]
Cool, can you work on it then send a PR, I'll appreciate 😊

**Comment by tenSunFree** [comment]
A PR has been sent, maybe you can refer to it.

**Comment by sharjeelmuzaffar** [comment]
can u please help me out with this error?

**Comment by HariAgus** [comment]
@sharjeelmuzaffar Hi, maybe you can try like this :

```
Modifier
    .verticalScroll(scrollState)
    .height(IntrinsicSize.Max)
```
