### ISSUE TITLE
App Installation 

### ISSUE THREAD

**Issue by Soham52** [joelkanyi/Muviz#97]
Sorry if it's dumb issue, but I can't seem to understand how you install the app?

**Comment by joelkanyi** [comment]
Hey @Soham52 I'll create a GitHub release tomorrow that will contain the app artifact (APK) then you can download it from there

**Comment by Soham52** [comment]
Tysm @joelkanyi  👍

**Comment by joelkanyi** [comment]
Download the APK here:

https://github.com/joelkanyi/Muviz/releases/tag/1.0.5
